<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AssessmentsSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('assessments')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('assessments')->insert([
            [
                'training_id' => 1,
                'title' => 'Evaluacion demo 1',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->subDays(55)->toDateString(),
                'end_date' => now()->subDays(45)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'title' => 'Evaluacion demo 2',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->subDays(45)->toDateString(),
                'end_date' => now()->subDays(35)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'title' => 'Evaluacion demo 3',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->subDays(40)->toDateString(),
                'end_date' => now()->subDays(30)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'title' => 'Evaluacion demo 4',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(4)->toDateString(),
                'end_date' => now()->addDays(11)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'title' => 'Evaluacion demo 5',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(5)->toDateString(),
                'end_date' => now()->addDays(12)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'title' => 'Evaluacion demo 6',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(6)->toDateString(),
                'end_date' => now()->addDays(13)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'title' => 'Evaluacion demo 7',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(7)->toDateString(),
                'end_date' => now()->addDays(14)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'title' => 'Evaluacion demo 8',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(8)->toDateString(),
                'end_date' => now()->addDays(15)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'title' => 'Evaluacion demo 9',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(9)->toDateString(),
                'end_date' => now()->addDays(16)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'title' => 'Evaluacion demo 10',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(10)->toDateString(),
                'end_date' => now()->addDays(17)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'title' => 'Evaluacion demo 11',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(11)->toDateString(),
                'end_date' => now()->addDays(18)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'title' => 'Evaluacion demo 12',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(12)->toDateString(),
                'end_date' => now()->addDays(19)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'title' => 'Evaluacion demo 13',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(13)->toDateString(),
                'end_date' => now()->addDays(20)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'title' => 'Evaluacion demo 14',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(14)->toDateString(),
                'end_date' => now()->addDays(21)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'title' => 'Evaluacion demo 15',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(15)->toDateString(),
                'end_date' => now()->addDays(22)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'title' => 'Evaluacion demo 16',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(16)->toDateString(),
                'end_date' => now()->addDays(23)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'title' => 'Evaluacion demo 17',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(17)->toDateString(),
                'end_date' => now()->addDays(24)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'title' => 'Evaluacion demo 18',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(18)->toDateString(),
                'end_date' => now()->addDays(25)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'title' => 'Evaluacion demo 19',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(19)->toDateString(),
                'end_date' => now()->addDays(26)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'title' => 'Evaluacion demo 20',
                'description' => 'Evaluacion generada para datos de prueba.',
                'start_date' => now()->addDays(20)->toDateString(),
                'end_date' => now()->addDays(27)->toDateString(),
                'allowed_attempts' => 2,
                'time_limit' => 60,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
