<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AssessmentAttemptsSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('assessment_attempts')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('assessment_attempts')->insert([
                [
                    'enrollment_id' => 1,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 2,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 3,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 21,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 22,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 23,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 41,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 42,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 43,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 44,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 45,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 46,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 47,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 48,
                    'assessment_id' => 1,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(10)->toDateString(),
                    'score' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 49,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 50,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 51,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 52,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 14,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 53,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 54,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 20,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 55,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 56,
                    'assessment_id' => 2,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(10)->toDateString(),
                    'score' => 19,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 57,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 58,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 18,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 59,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 60,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 17,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 61,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 62,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 16,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 63,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 9,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 64,
                    'assessment_id' => 3,
                    'number' => 1,
                    'date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(10)->toDateString(),
                    'score' => 15,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
