<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CoursesSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('courses')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('courses')->insert([
            [
                'specialty_id' => 1,
                'banner_path' => null,
                'title' => 'Excel profesional',
                'abbreviation' => 'EXPRO',
                'description' => 'Curso de demostración de Excel profesional',
                'hours_count' => 22,
                'reference_price' => 135,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 2,
                'banner_path' => null,
                'title' => 'Excel macros',
                'abbreviation' => 'EXMAC',
                'description' => 'Curso de demostración de Excel macros',
                'hours_count' => 24,
                'reference_price' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 3,
                'banner_path' => null,
                'title' => 'Excel financiero',
                'abbreviation' => 'EXFIN',
                'description' => 'Curso de demostración de Excel financiero',
                'hours_count' => 26,
                'reference_price' => 165,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 4,
                'banner_path' => null,
                'title' => 'Power BI',
                'abbreviation' => 'POWBI',
                'description' => 'Curso de demostración de Power BI',
                'hours_count' => 28,
                'reference_price' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 5,
                'banner_path' => null,
                'title' => 'Microsoft Project',
                'abbreviation' => 'MSPRO',
                'description' => 'Curso de demostración de Microsoft Project',
                'hours_count' => 30,
                'reference_price' => 195,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 6,
                'banner_path' => null,
                'title' => 'AutoCAD profesional',
                'abbreviation' => 'ACPRO',
                'description' => 'Curso de demostración de AutoCAD profesional',
                'hours_count' => 32,
                'reference_price' => 210,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 7,
                'banner_path' => null,
                'title' => 'Revit profesional',
                'abbreviation' => 'REPRO',
                'description' => 'Curso de demostración de Revit profesional',
                'hours_count' => 34,
                'reference_price' => 225,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 8,
                'banner_path' => null,
                'title' => 'Python',
                'abbreviation' => 'PYTH',
                'description' => 'Curso demo de Python',
                'hours_count' => 36,
                'reference_price' => 240,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 9,
                'banner_path' => null,
                'title' => 'Inteligencia artificial',
                'abbreviation' => 'IA',
                'description' => 'Curso de demostración de inteligencia artificial',
                'hours_count' => 38,
                'reference_price' => 255,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 10,
                'banner_path' => null,
                'title' => 'SAP ERP',
                'abbreviation' => 'SAP',
                'description' => 'Curso demo de SAP ERP',
                'hours_count' => 40,
                'reference_price' => 270,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 11,
                'banner_path' => null,
                'title' => 'Marketing Digital',
                'abbreviation' => 'MKDIG',
                'description' => 'Curso demo de Marketing Digital',
                'hours_count' => 42,
                'reference_price' => 285,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 12,
                'banner_path' => null,
                'title' => 'Edición de video',
                'abbreviation' => 'EDVID',
                'description' => 'Curso de demostración de edición de video',
                'hours_count' => 44,
                'reference_price' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 13,
                'banner_path' => null,
                'title' => 'Oratoria',
                'abbreviation' => 'ORAT',
                'description' => 'Curso demo de Oratoria',
                'hours_count' => 46,
                'reference_price' => 315,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 14,
                'banner_path' => null,
                'title' => 'Ciberseguridad básica',
                'abbreviation' => 'CIBSEC',
                'description' => 'Curso de demostración de ciberseguridad básica',
                'hours_count' => 48,
                'reference_price' => 330,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 15,
                'banner_path' => null,
                'title' => 'Redes Cisco',
                'abbreviation' => 'RSCIS',
                'description' => 'Curso demo de Redes Cisco',
                'hours_count' => 50,
                'reference_price' => 345,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 16,
                'banner_path' => null,
                'title' => 'Diseño gráfico',
                'abbreviation' => 'DSGRA',
                'description' => 'Curso de demostración de diseño gráfico',
                'hours_count' => 52,
                'reference_price' => 360,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 17,
                'banner_path' => null,
                'title' => 'Contabilidad Digital',
                'abbreviation' => 'CTDIG',
                'description' => 'Curso demo de Contabilidad Digital',
                'hours_count' => 54,
                'reference_price' => 375,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 18,
                'banner_path' => null,
                'title' => 'Gestión de ventas',
                'abbreviation' => 'GVENT',
                'description' => 'Curso de demostración de gestión de ventas',
                'hours_count' => 56,
                'reference_price' => 390,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 19,
                'banner_path' => null,
                'title' => 'Logística integral',
                'abbreviation' => 'LOGINT',
                'description' => 'Curso de demostración de logística integral',
                'hours_count' => 58,
                'reference_price' => 405,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'specialty_id' => 20,
                'banner_path' => null,
                'title' => 'Emprendimiento',
                'abbreviation' => 'EMPRE',
                'description' => 'Curso demo de Emprendimiento',
                'hours_count' => 60,
                'reference_price' => 420,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
