<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class EnrollmentsSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('enrollments')->truncate();
        Schema::enableForeignKeyConstraints();

        $mariaTeacher = \App\Models\User::where('username', 'maria.lopez.teacher')->first();
        $otherTraining = \App\Models\Training::query();

        if ($mariaTeacher) {
            $otherTraining = \App\Models\Training::where('teacher_id', '!=', $mariaTeacher->user_id)->first();
        }

        if ($mariaTeacher && $otherTraining) {
            \App\Models\Enrollment::create([
                'student_id' => $mariaTeacher->user_id,
                'training_id' => $otherTraining->training_id,
                'administrator_id' => 1,
                'enrollment_date' => now(),
                'scholarship_percentage' => 0,
                'status' => 'A',
            ]);
        }

        DB::table('enrollments')->insert([
            [
                'training_id' => 1,
                'student_id' => 7,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 8,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 9,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 10,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 11,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 12,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 13,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 14,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 15,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 16,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 17,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 18,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 19,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(7)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 20,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(6)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 7,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(5)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 8,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(4)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 9,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(3)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 10,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(2)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 11,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(1)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 12,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(0)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 21,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 22,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 23,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 24,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 25,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 26,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 27,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 28,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 29,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 30,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 21,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 22,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 23,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 24,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(7)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 25,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(6)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 26,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(5)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 27,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(4)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 28,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(3)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 29,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(2)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 30,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(1)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('enrollments')->insert([
            [
                'training_id' => 1,
                'student_id' => 31,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 32,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 33,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 34,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 35,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 36,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 37,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 1,
                'student_id' => 38,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(61)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 39,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 40,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 41,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 42,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 43,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 44,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 45,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 2,
                'student_id' => 46,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(51)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 47,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 48,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 49,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 50,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 51,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 52,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 53,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 3,
                'student_id' => 54,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(46)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 55,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(26)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 56,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(25)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 57,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(24)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 58,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(23)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 59,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(22)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 60,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(21)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 61,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(20)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 4,
                'student_id' => 62,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 63,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(25)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 64,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(24)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 65,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(23)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 66,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(22)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 31,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(21)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 32,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(20)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 33,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 5,
                'student_id' => 34,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 35,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(24)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 36,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(23)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 37,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(22)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 38,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(21)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 39,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(20)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 40,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 41,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 6,
                'student_id' => 42,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 43,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(23)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 44,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(22)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 45,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(21)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 46,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(20)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 47,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 48,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 49,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 7,
                'student_id' => 50,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 51,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(22)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 52,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(21)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 53,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(20)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 54,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 55,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 56,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 57,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 8,
                'student_id' => 58,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 59,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(21)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 60,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(20)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 61,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 62,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 63,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 64,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 65,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 9,
                'student_id' => 66,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 31,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(20)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 32,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 33,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 34,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 35,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 36,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 37,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 10,
                'student_id' => 38,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 39,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(19)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 40,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 41,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 42,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 43,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 44,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 45,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 11,
                'student_id' => 46,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 47,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(18)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 48,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 49,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 50,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 51,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 52,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 53,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 12,
                'student_id' => 54,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 55,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(17)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 56,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 57,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 58,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 59,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 60,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 61,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 13,
                'student_id' => 62,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 63,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(16)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 64,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 65,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 66,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 31,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 32,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 33,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 14,
                'student_id' => 34,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 35,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(15)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 36,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 37,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 38,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 39,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 40,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 41,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 15,
                'student_id' => 42,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 43,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(14)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 44,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 45,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 46,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 47,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 48,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 49,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 16,
                'student_id' => 50,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(7)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 51,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(13)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 52,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 53,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 54,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 55,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 56,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 57,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(7)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 17,
                'student_id' => 58,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(6)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 59,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(12)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 60,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 61,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 62,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 63,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 64,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(7)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 65,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(6)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 18,
                'student_id' => 66,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(5)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 31,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(11)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 32,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 33,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 34,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 35,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(7)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 36,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(6)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 37,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(5)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 19,
                'student_id' => 38,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(4)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 39,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(10)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 40,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(9)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 41,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(8)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 42,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(7)->toDateString(),
                'scholarship_percentage' => 15,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 43,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(6)->toDateString(),
                'scholarship_percentage' => 20,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 44,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(5)->toDateString(),
                'scholarship_percentage' => 0,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 45,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(4)->toDateString(),
                'scholarship_percentage' => 5,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'training_id' => 20,
                'student_id' => 46,
                'administrator_id' => 1,
                'enrollment_date' => now()->subDays(3)->toDateString(),
                'scholarship_percentage' => 10,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
