<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PaymentsSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('payments')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('payments')->insert([
            [
                'enrollment_id' => 1,
                'payment_method_id' => 1,
                'date' => now()->subDays(19)->toDateString(),
                'installment' => 1,
                'amount' => 110,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 2,
                'payment_method_id' => 2,
                'date' => now()->subDays(18)->toDateString(),
                'installment' => 1,
                'amount' => 120,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 3,
                'payment_method_id' => 3,
                'date' => now()->subDays(17)->toDateString(),
                'installment' => 1,
                'amount' => 130,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 4,
                'payment_method_id' => 4,
                'date' => now()->subDays(16)->toDateString(),
                'installment' => 1,
                'amount' => 140,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 5,
                'payment_method_id' => 5,
                'date' => now()->subDays(15)->toDateString(),
                'installment' => 1,
                'amount' => 150,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 6,
                'payment_method_id' => 6,
                'date' => now()->subDays(14)->toDateString(),
                'installment' => 1,
                'amount' => 160,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 7,
                'payment_method_id' => 7,
                'date' => now()->subDays(13)->toDateString(),
                'installment' => 1,
                'amount' => 170,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 8,
                'payment_method_id' => 8,
                'date' => now()->subDays(12)->toDateString(),
                'installment' => 1,
                'amount' => 180,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 9,
                'payment_method_id' => 9,
                'date' => now()->subDays(11)->toDateString(),
                'installment' => 1,
                'amount' => 190,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 10,
                'payment_method_id' => 10,
                'date' => now()->subDays(10)->toDateString(),
                'installment' => 1,
                'amount' => 200,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 11,
                'payment_method_id' => 11,
                'date' => now()->subDays(9)->toDateString(),
                'installment' => 1,
                'amount' => 210,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 12,
                'payment_method_id' => 12,
                'date' => now()->subDays(8)->toDateString(),
                'installment' => 1,
                'amount' => 220,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 13,
                'payment_method_id' => 13,
                'date' => now()->subDays(7)->toDateString(),
                'installment' => 1,
                'amount' => 230,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 14,
                'payment_method_id' => 14,
                'date' => now()->subDays(6)->toDateString(),
                'installment' => 1,
                'amount' => 240,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 15,
                'payment_method_id' => 15,
                'date' => now()->subDays(5)->toDateString(),
                'installment' => 1,
                'amount' => 250,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 16,
                'payment_method_id' => 16,
                'date' => now()->subDays(4)->toDateString(),
                'installment' => 1,
                'amount' => 260,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 17,
                'payment_method_id' => 17,
                'date' => now()->subDays(3)->toDateString(),
                'installment' => 1,
                'amount' => 270,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 18,
                'payment_method_id' => 18,
                'date' => now()->subDays(2)->toDateString(),
                'installment' => 1,
                'amount' => 280,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 19,
                'payment_method_id' => 19,
                'date' => now()->subDays(1)->toDateString(),
                'installment' => 1,
                'amount' => 290,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'enrollment_id' => 20,
                'payment_method_id' => 20,
                'date' => now()->subDays(0)->toDateString(),
                'installment' => 1,
                'amount' => 300,
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
