<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class PeopleSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('people')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('people')->insert([
            [
                'last_names' => 'Gomez Perez',
                'first_names' => 'Juan Carlos',
                'document_type' => 'DNI',
                'document_number' => '10000001',
                'phone' => '987654321',
                'address' => 'Av. Siempre Viva 123',
                'email' => 'juan.gomez.001@example.com',
                'gender' => 'M',
                'birth_date' => '1990-05-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Lopez Ramirez',
                'first_names' => 'Maria Elena',
                'document_type' => 'DNI',
                'document_number' => '10000002',
                'phone' => '912345678',
                'address' => 'Jr. Las Flores 456',
                'email' => 'maria.lopez.002@example.com',
                'gender' => 'F',
                'birth_date' => '1995-08-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Torres Diaz',
                'first_names' => 'Luis Alberto',
                'document_type' => 'DNI',
                'document_number' => '10000003',
                'phone' => '998877665',
                'address' => 'Calle Sol 789',
                'email' => 'luis.torres.003@example.com',
                'gender' => 'M',
                'birth_date' => '1988-03-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Rojas Castillo',
                'first_names' => 'Ana Lucia',
                'document_type' => 'DNI',
                'document_number' => '10000004',
                'phone' => '955443322',
                'address' => 'Av. Peru 321',
                'email' => 'ana.rojas.004@example.com',
                'gender' => 'F',
                'birth_date' => '2000-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Martinez Lopez',
                'first_names' => 'Carlos Eduardo',
                'document_type' => 'DNI',
                'document_number' => '10000005',
                'phone' => '966554433',
                'address' => 'Jr. Lima 123',
                'email' => 'carlos.martinez.005@example.com',
                'gender' => 'M',
                'birth_date' => '1992-03-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Garcia Sanchez',
                'first_names' => 'Laura Sofia',
                'document_type' => 'DNI',
                'document_number' => '10000006',
                'phone' => '977665544',
                'address' => 'Av. Arequipa 456',
                'email' => 'laura.garcia.006@example.com',
                'gender' => 'F',
                'birth_date' => '1994-07-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Hernandez Ruiz',
                'first_names' => 'Miguel Angel',
                'document_type' => 'DNI',
                'document_number' => '10000007',
                'phone' => '988776655',
                'address' => 'Calle Cusco 789',
                'email' => 'miguel.hernandez.007@example.com',
                'gender' => 'M',
                'birth_date' => '1989-12-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Jimenez Morales',
                'first_names' => 'Isabel Cristina',
                'document_type' => 'DNI',
                'document_number' => '10000008',
                'phone' => '999887766',
                'address' => 'Jr. Trujillo 101',
                'email' => 'isabel.jimenez.008@example.com',
                'gender' => 'F',
                'birth_date' => '1996-04-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Perez Alvarez',
                'first_names' => 'Diego Fernando',
                'document_type' => 'DNI',
                'document_number' => '10000009',
                'phone' => '911223344',
                'address' => 'Av. Piura 202',
                'email' => 'diego.perez.009@example.com',
                'gender' => 'M',
                'birth_date' => '1991-09-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Ramirez Torres',
                'first_names' => 'Valentina Andrea',
                'document_type' => 'DNI',
                'document_number' => '10000010',
                'phone' => '922334455',
                'address' => 'Calle Chiclayo 303',
                'email' => 'valentina.ramirez.010@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Flores Castillo',
                'first_names' => 'Andres Jose',
                'document_type' => 'DNI',
                'document_number' => '10000011',
                'phone' => '933445566',
                'address' => 'Jr. Ica 404',
                'email' => 'andres.flores.011@example.com',
                'gender' => 'M',
                'birth_date' => '1993-06-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Gutierrez Vargas',
                'first_names' => 'Camila Sofia',
                'document_type' => 'DNI',
                'document_number' => '10000012',
                'phone' => '944556677',
                'address' => 'Av. Tacna 505',
                'email' => 'camila.gutierrez.012@example.com',
                'gender' => 'F',
                'birth_date' => '1997-11-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Reyes Mendoza',
                'first_names' => 'Javier Alejandro',
                'document_type' => 'DNI',
                'document_number' => '10000013',
                'phone' => '955667788',
                'address' => 'Calle Puno 606',
                'email' => 'javier.reyes.013@example.com',
                'gender' => 'M',
                'birth_date' => '1990-02-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Morales Silva',
                'first_names' => 'Gabriela Lucia',
                'document_type' => 'DNI',
                'document_number' => '10000014',
                'phone' => '966778899',
                'address' => 'Jr. Huancayo 707',
                'email' => 'gabriela.morales.014@example.com',
                'gender' => 'F',
                'birth_date' => '1995-05-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Ortiz Chavez',
                'first_names' => 'Roberto Carlos',
                'document_type' => 'DNI',
                'document_number' => '10000015',
                'phone' => '977889900',
                'address' => 'Av. Ayacucho 808',
                'email' => 'roberto.ortiz.015@example.com',
                'gender' => 'M',
                'birth_date' => '1987-08-27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Delgado Rios',
                'first_names' => 'Natalia Andrea',
                'document_type' => 'DNI',
                'document_number' => '10000016',
                'phone' => '988990011',
                'address' => 'Calle Cajamarca 909',
                'email' => 'natalia.delgado.016@example.com',
                'gender' => 'F',
                'birth_date' => '1999-12-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Sanchez Guzman',
                'first_names' => 'Fernando Luis',
                'document_type' => 'DNI',
                'document_number' => '10000017',
                'phone' => '999001122',
                'address' => 'Jr. Lambayeque 1010',
                'email' => 'fernando.sanchez.017@example.com',
                'gender' => 'M',
                'birth_date' => '1992-10-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Vargas Leon',
                'first_names' => 'Monica Paola',
                'document_type' => 'DNI',
                'document_number' => '10000018',
                'phone' => '911112233',
                'address' => 'Av. Loreto 1111',
                'email' => 'monica.vargas.018@example.com',
                'gender' => 'F',
                'birth_date' => '1994-03-21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Castro Medina',
                'first_names' => 'Eduardo Miguel',
                'document_type' => 'DNI',
                'document_number' => '10000019',
                'phone' => '922223344',
                'address' => 'Calle Amazonas 1212',
                'email' => 'eduardo.castro.019@example.com',
                'gender' => 'M',
                'birth_date' => '1988-07-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Romero Aguilar',
                'first_names' => 'Patricia Elena',
                'document_type' => 'DNI',
                'document_number' => '10000020',
                'phone' => '933334455',
                'address' => 'Jr. San Martin 1313',
                'email' => 'patricia.romero.020@example.com',
                'gender' => 'F',
                'birth_date' => '1996-09-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Mendoza Cruz',
                'first_names' => 'Sofia Valeria',
                'document_type' => 'DNI',
                'document_number' => '10000021',
                'phone' => '944445566',
                'address' => 'Av. Grau 1414',
                'email' => 'sofia.mendoza.021@example.com',
                'gender' => 'F',
                'birth_date' => '1998-02-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Quispe Huaman',
                'first_names' => 'Mateo Andres',
                'document_type' => 'DNI',
                'document_number' => '10000022',
                'phone' => '955556677',
                'address' => 'Jr. Los Olivos 1515',
                'email' => 'mateo.quispe.022@example.com',
                'gender' => 'M',
                'birth_date' => '1997-04-24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Navarro Salas',
                'first_names' => 'Lucia Fernanda',
                'document_type' => 'DNI',
                'document_number' => '10000023',
                'phone' => '966667788',
                'address' => 'Calle Union 1616',
                'email' => 'lucia.navarro.023@example.com',
                'gender' => 'F',
                'birth_date' => '1999-06-18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Vega Ponce',
                'first_names' => 'Sebastian Ivan',
                'document_type' => 'DNI',
                'document_number' => '10000024',
                'phone' => '977778899',
                'address' => 'Av. Colonial 1717',
                'email' => 'sebastian.vega.024@example.com',
                'gender' => 'M',
                'birth_date' => '1995-10-02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Campos Rivas',
                'first_names' => 'Daniela Maria',
                'document_type' => 'DNI',
                'document_number' => '10000025',
                'phone' => '988889900',
                'address' => 'Jr. Primavera 1818',
                'email' => 'daniela.campos.025@example.com',
                'gender' => 'F',
                'birth_date' => '1996-12-29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Paredes Luna',
                'first_names' => 'Ricardo Manuel',
                'document_type' => 'DNI',
                'document_number' => '10000026',
                'phone' => '999990011',
                'address' => 'Calle Comercio 1919',
                'email' => 'ricardo.paredes.026@example.com',
                'gender' => 'M',
                'birth_date' => '1994-01-07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Salazar Pena',
                'first_names' => 'Elena Patricia',
                'document_type' => 'DNI',
                'document_number' => '10000027',
                'phone' => '911110022',
                'address' => 'Av. Universitaria 2020',
                'email' => 'elena.salazar.027@example.com',
                'gender' => 'F',
                'birth_date' => '1998-08-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Cardenas Soto',
                'first_names' => 'Piero Gabriel',
                'document_type' => 'DNI',
                'document_number' => '10000028',
                'phone' => '922220033',
                'address' => 'Jr. Progreso 2121',
                'email' => 'piero.cardenas.028@example.com',
                'gender' => 'M',
                'birth_date' => '1993-11-23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Soto Molina',
                'first_names' => 'Mariana Isabel',
                'document_type' => 'DNI',
                'document_number' => '10000029',
                'phone' => '933330044',
                'address' => 'Calle Central 2222',
                'email' => 'mariana.soto.029@example.com',
                'gender' => 'F',
                'birth_date' => '1997-07-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Rivera Torres',
                'first_names' => 'Alonso Nicolas',
                'document_type' => 'DNI',
                'document_number' => '10000030',
                'phone' => '944440055',
                'address' => 'Av. Industrial 2323',
                'email' => 'alonso.rivera.030@example.com',
                'gender' => 'M',
                'birth_date' => '1992-05-19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('people')->insert([
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 31',
                'document_type' => 'DNI',
                'document_number' => '10000031',
                'phone' => '900000031',
                'address' => 'Direccion demo 31',
                'email' => 'estudiante31@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 32',
                'document_type' => 'DNI',
                'document_number' => '10000032',
                'phone' => '900000032',
                'address' => 'Direccion demo 32',
                'email' => 'estudiante32@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 33',
                'document_type' => 'DNI',
                'document_number' => '10000033',
                'phone' => '900000033',
                'address' => 'Direccion demo 33',
                'email' => 'estudiante33@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 34',
                'document_type' => 'DNI',
                'document_number' => '10000034',
                'phone' => '900000034',
                'address' => 'Direccion demo 34',
                'email' => 'estudiante34@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 35',
                'document_type' => 'DNI',
                'document_number' => '10000035',
                'phone' => '900000035',
                'address' => 'Direccion demo 35',
                'email' => 'estudiante35@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 36',
                'document_type' => 'DNI',
                'document_number' => '10000036',
                'phone' => '900000036',
                'address' => 'Direccion demo 36',
                'email' => 'estudiante36@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 37',
                'document_type' => 'DNI',
                'document_number' => '10000037',
                'phone' => '900000037',
                'address' => 'Direccion demo 37',
                'email' => 'estudiante37@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 38',
                'document_type' => 'DNI',
                'document_number' => '10000038',
                'phone' => '900000038',
                'address' => 'Direccion demo 38',
                'email' => 'estudiante38@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 39',
                'document_type' => 'DNI',
                'document_number' => '10000039',
                'phone' => '900000039',
                'address' => 'Direccion demo 39',
                'email' => 'estudiante39@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 40',
                'document_type' => 'DNI',
                'document_number' => '10000040',
                'phone' => '900000040',
                'address' => 'Direccion demo 40',
                'email' => 'estudiante40@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 41',
                'document_type' => 'DNI',
                'document_number' => '10000041',
                'phone' => '900000041',
                'address' => 'Direccion demo 41',
                'email' => 'estudiante41@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 42',
                'document_type' => 'DNI',
                'document_number' => '10000042',
                'phone' => '900000042',
                'address' => 'Direccion demo 42',
                'email' => 'estudiante42@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 43',
                'document_type' => 'DNI',
                'document_number' => '10000043',
                'phone' => '900000043',
                'address' => 'Direccion demo 43',
                'email' => 'estudiante43@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 44',
                'document_type' => 'DNI',
                'document_number' => '10000044',
                'phone' => '900000044',
                'address' => 'Direccion demo 44',
                'email' => 'estudiante44@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 45',
                'document_type' => 'DNI',
                'document_number' => '10000045',
                'phone' => '900000045',
                'address' => 'Direccion demo 45',
                'email' => 'estudiante45@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 46',
                'document_type' => 'DNI',
                'document_number' => '10000046',
                'phone' => '900000046',
                'address' => 'Direccion demo 46',
                'email' => 'estudiante46@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 47',
                'document_type' => 'DNI',
                'document_number' => '10000047',
                'phone' => '900000047',
                'address' => 'Direccion demo 47',
                'email' => 'estudiante47@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 48',
                'document_type' => 'DNI',
                'document_number' => '10000048',
                'phone' => '900000048',
                'address' => 'Direccion demo 48',
                'email' => 'estudiante48@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 49',
                'document_type' => 'DNI',
                'document_number' => '10000049',
                'phone' => '900000049',
                'address' => 'Direccion demo 49',
                'email' => 'estudiante49@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 50',
                'document_type' => 'DNI',
                'document_number' => '10000050',
                'phone' => '900000050',
                'address' => 'Direccion demo 50',
                'email' => 'estudiante50@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 51',
                'document_type' => 'DNI',
                'document_number' => '10000051',
                'phone' => '900000051',
                'address' => 'Direccion demo 51',
                'email' => 'estudiante51@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 52',
                'document_type' => 'DNI',
                'document_number' => '10000052',
                'phone' => '900000052',
                'address' => 'Direccion demo 52',
                'email' => 'estudiante52@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 53',
                'document_type' => 'DNI',
                'document_number' => '10000053',
                'phone' => '900000053',
                'address' => 'Direccion demo 53',
                'email' => 'estudiante53@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 54',
                'document_type' => 'DNI',
                'document_number' => '10000054',
                'phone' => '900000054',
                'address' => 'Direccion demo 54',
                'email' => 'estudiante54@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 55',
                'document_type' => 'DNI',
                'document_number' => '10000055',
                'phone' => '900000055',
                'address' => 'Direccion demo 55',
                'email' => 'estudiante55@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 56',
                'document_type' => 'DNI',
                'document_number' => '10000056',
                'phone' => '900000056',
                'address' => 'Direccion demo 56',
                'email' => 'estudiante56@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 57',
                'document_type' => 'DNI',
                'document_number' => '10000057',
                'phone' => '900000057',
                'address' => 'Direccion demo 57',
                'email' => 'estudiante57@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 58',
                'document_type' => 'DNI',
                'document_number' => '10000058',
                'phone' => '900000058',
                'address' => 'Direccion demo 58',
                'email' => 'estudiante58@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 59',
                'document_type' => 'DNI',
                'document_number' => '10000059',
                'phone' => '900000059',
                'address' => 'Direccion demo 59',
                'email' => 'estudiante59@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 60',
                'document_type' => 'DNI',
                'document_number' => '10000060',
                'phone' => '900000060',
                'address' => 'Direccion demo 60',
                'email' => 'estudiante60@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 61',
                'document_type' => 'DNI',
                'document_number' => '10000061',
                'phone' => '900000061',
                'address' => 'Direccion demo 61',
                'email' => 'estudiante61@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 62',
                'document_type' => 'DNI',
                'document_number' => '10000062',
                'phone' => '900000062',
                'address' => 'Direccion demo 62',
                'email' => 'estudiante62@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 63',
                'document_type' => 'DNI',
                'document_number' => '10000063',
                'phone' => '900000063',
                'address' => 'Direccion demo 63',
                'email' => 'estudiante63@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 64',
                'document_type' => 'DNI',
                'document_number' => '10000064',
                'phone' => '900000064',
                'address' => 'Direccion demo 64',
                'email' => 'estudiante64@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 65',
                'document_type' => 'DNI',
                'document_number' => '10000065',
                'phone' => '900000065',
                'address' => 'Direccion demo 65',
                'email' => 'estudiante65@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_names' => 'Demo LMS',
                'first_names' => 'Estudiante 66',
                'document_type' => 'DNI',
                'document_number' => '10000066',
                'phone' => '900000066',
                'address' => 'Direccion demo 66',
                'email' => 'estudiante66@example.com',
                'gender' => 'M',
                'birth_date' => '1998-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
