<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProgressSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('progress')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('progress')->insert([
                [
                    'enrollment_id' => 1,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 2,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 3,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 4,
                    'content_id' => 4,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 5,
                    'content_id' => 5,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 6,
                    'content_id' => 6,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 7,
                    'content_id' => 7,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 8,
                    'content_id' => 8,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 9,
                    'content_id' => 9,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 10,
                    'content_id' => 10,
                    'percentage' => 50,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 11,
                    'content_id' => 11,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 12,
                    'content_id' => 12,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 13,
                    'content_id' => 13,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(7)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 14,
                    'content_id' => 14,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(6)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 15,
                    'content_id' => 15,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(5)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 16,
                    'content_id' => 16,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(4)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 17,
                    'content_id' => 17,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(3)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 18,
                    'content_id' => 18,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(2)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 19,
                    'content_id' => 19,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(1)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 20,
                    'content_id' => 20,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(0)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 21,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 22,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 23,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 24,
                    'content_id' => 4,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 25,
                    'content_id' => 5,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 26,
                    'content_id' => 6,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 27,
                    'content_id' => 7,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 28,
                    'content_id' => 8,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 29,
                    'content_id' => 9,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 30,
                    'content_id' => 10,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 31,
                    'content_id' => 11,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 32,
                    'content_id' => 12,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 33,
                    'content_id' => 13,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 34,
                    'content_id' => 14,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(7)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 35,
                    'content_id' => 15,
                    'percentage' => 15,
                    'activity_date' => Carbon::parse(now()->subDays(6)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 36,
                    'content_id' => 16,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(5)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 37,
                    'content_id' => 17,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(4)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 38,
                    'content_id' => 18,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(3)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 39,
                    'content_id' => 19,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(2)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 40,
                    'content_id' => 20,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(1)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 41,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 42,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 43,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 44,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 45,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 46,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 47,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 48,
                    'content_id' => 1,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(61)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 49,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 50,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 51,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 52,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 53,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 54,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 55,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 56,
                    'content_id' => 2,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(51)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 57,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 58,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 59,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 60,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 61,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 62,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 63,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 64,
                    'content_id' => 3,
                    'percentage' => 100,
                    'activity_date' => Carbon::parse(now()->subDays(46)->toDateString())->addDays(5)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 65,
                    'content_id' => 4,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(26)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 66,
                    'content_id' => 4,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(25)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 67,
                    'content_id' => 4,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(24)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 68,
                    'content_id' => 4,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(23)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 69,
                    'content_id' => 4,
                    'percentage' => 15,
                    'activity_date' => Carbon::parse(now()->subDays(22)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 70,
                    'content_id' => 4,
                    'percentage' => 50,
                    'activity_date' => Carbon::parse(now()->subDays(21)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 71,
                    'content_id' => 4,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(20)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 72,
                    'content_id' => 4,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 73,
                    'content_id' => 5,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(25)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 74,
                    'content_id' => 5,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(24)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 75,
                    'content_id' => 5,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(23)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 76,
                    'content_id' => 5,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(22)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 77,
                    'content_id' => 5,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(21)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 78,
                    'content_id' => 5,
                    'percentage' => 15,
                    'activity_date' => Carbon::parse(now()->subDays(20)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 79,
                    'content_id' => 5,
                    'percentage' => 50,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 80,
                    'content_id' => 5,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 81,
                    'content_id' => 6,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(24)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 82,
                    'content_id' => 6,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(23)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 83,
                    'content_id' => 6,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(22)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 84,
                    'content_id' => 6,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(21)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 85,
                    'content_id' => 6,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(20)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 86,
                    'content_id' => 6,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 87,
                    'content_id' => 6,
                    'percentage' => 15,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 88,
                    'content_id' => 6,
                    'percentage' => 50,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 89,
                    'content_id' => 7,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(23)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 90,
                    'content_id' => 7,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(22)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 91,
                    'content_id' => 7,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(21)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 92,
                    'content_id' => 7,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(20)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 93,
                    'content_id' => 7,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 94,
                    'content_id' => 7,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 95,
                    'content_id' => 7,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 96,
                    'content_id' => 7,
                    'percentage' => 15,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 97,
                    'content_id' => 8,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(22)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 98,
                    'content_id' => 8,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(21)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 99,
                    'content_id' => 8,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(20)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 100,
                    'content_id' => 8,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 101,
                    'content_id' => 8,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 102,
                    'content_id' => 8,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 103,
                    'content_id' => 8,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 104,
                    'content_id' => 8,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 105,
                    'content_id' => 9,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(21)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 106,
                    'content_id' => 9,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(20)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 107,
                    'content_id' => 9,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 108,
                    'content_id' => 9,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 109,
                    'content_id' => 9,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 110,
                    'content_id' => 9,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 111,
                    'content_id' => 9,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 112,
                    'content_id' => 9,
                    'percentage' => 40,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 113,
                    'content_id' => 10,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(20)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 114,
                    'content_id' => 10,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 115,
                    'content_id' => 10,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 116,
                    'content_id' => 10,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 117,
                    'content_id' => 10,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 118,
                    'content_id' => 10,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 119,
                    'content_id' => 10,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 120,
                    'content_id' => 10,
                    'percentage' => 5,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 121,
                    'content_id' => 11,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(19)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 122,
                    'content_id' => 11,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 123,
                    'content_id' => 11,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 124,
                    'content_id' => 11,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 125,
                    'content_id' => 11,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 126,
                    'content_id' => 11,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 127,
                    'content_id' => 11,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 128,
                    'content_id' => 11,
                    'percentage' => 65,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 129,
                    'content_id' => 12,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(18)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 130,
                    'content_id' => 12,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 131,
                    'content_id' => 12,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 132,
                    'content_id' => 12,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 133,
                    'content_id' => 12,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 134,
                    'content_id' => 12,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 135,
                    'content_id' => 12,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 136,
                    'content_id' => 12,
                    'percentage' => 30,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 137,
                    'content_id' => 13,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(17)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 138,
                    'content_id' => 13,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 139,
                    'content_id' => 13,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 140,
                    'content_id' => 13,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 141,
                    'content_id' => 13,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 142,
                    'content_id' => 13,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 143,
                    'content_id' => 13,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 144,
                    'content_id' => 13,
                    'percentage' => 90,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 145,
                    'content_id' => 14,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(16)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 146,
                    'content_id' => 14,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 147,
                    'content_id' => 14,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 148,
                    'content_id' => 14,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 149,
                    'content_id' => 14,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 150,
                    'content_id' => 14,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 151,
                    'content_id' => 14,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 152,
                    'content_id' => 14,
                    'percentage' => 55,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 153,
                    'content_id' => 15,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(15)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 154,
                    'content_id' => 15,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 155,
                    'content_id' => 15,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 156,
                    'content_id' => 15,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 157,
                    'content_id' => 15,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 158,
                    'content_id' => 15,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 159,
                    'content_id' => 15,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 160,
                    'content_id' => 15,
                    'percentage' => 20,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 161,
                    'content_id' => 16,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(14)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 162,
                    'content_id' => 16,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 163,
                    'content_id' => 16,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 164,
                    'content_id' => 16,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 165,
                    'content_id' => 16,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 166,
                    'content_id' => 16,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 167,
                    'content_id' => 16,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 168,
                    'content_id' => 16,
                    'percentage' => 80,
                    'activity_date' => Carbon::parse(now()->subDays(7)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 169,
                    'content_id' => 17,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(13)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 170,
                    'content_id' => 17,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 171,
                    'content_id' => 17,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 172,
                    'content_id' => 17,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 173,
                    'content_id' => 17,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 174,
                    'content_id' => 17,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 175,
                    'content_id' => 17,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(7)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 176,
                    'content_id' => 17,
                    'percentage' => 45,
                    'activity_date' => Carbon::parse(now()->subDays(6)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 177,
                    'content_id' => 18,
                    'percentage' => 50,
                    'activity_date' => Carbon::parse(now()->subDays(12)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 178,
                    'content_id' => 18,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 179,
                    'content_id' => 18,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 180,
                    'content_id' => 18,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 181,
                    'content_id' => 18,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 182,
                    'content_id' => 18,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(7)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 183,
                    'content_id' => 18,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(6)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 184,
                    'content_id' => 18,
                    'percentage' => 10,
                    'activity_date' => Carbon::parse(now()->subDays(5)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 185,
                    'content_id' => 19,
                    'percentage' => 15,
                    'activity_date' => Carbon::parse(now()->subDays(11)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 186,
                    'content_id' => 19,
                    'percentage' => 50,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 187,
                    'content_id' => 19,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 188,
                    'content_id' => 19,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 189,
                    'content_id' => 19,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(7)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 190,
                    'content_id' => 19,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(6)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 191,
                    'content_id' => 19,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(5)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 192,
                    'content_id' => 19,
                    'percentage' => 70,
                    'activity_date' => Carbon::parse(now()->subDays(4)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 193,
                    'content_id' => 20,
                    'percentage' => 75,
                    'activity_date' => Carbon::parse(now()->subDays(10)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 194,
                    'content_id' => 20,
                    'percentage' => 15,
                    'activity_date' => Carbon::parse(now()->subDays(9)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 195,
                    'content_id' => 20,
                    'percentage' => 50,
                    'activity_date' => Carbon::parse(now()->subDays(8)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 196,
                    'content_id' => 20,
                    'percentage' => 85,
                    'activity_date' => Carbon::parse(now()->subDays(7)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 197,
                    'content_id' => 20,
                    'percentage' => 25,
                    'activity_date' => Carbon::parse(now()->subDays(6)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 198,
                    'content_id' => 20,
                    'percentage' => 60,
                    'activity_date' => Carbon::parse(now()->subDays(5)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 199,
                    'content_id' => 20,
                    'percentage' => 0,
                    'activity_date' => Carbon::parse(now()->subDays(4)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'enrollment_id' => 200,
                    'content_id' => 20,
                    'percentage' => 35,
                    'activity_date' => Carbon::parse(now()->subDays(3)->toDateString())->addDays(2)->toDateString(),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
