<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TaskSubmissionSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('task_submissions')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('task_submissions')->insert([
            [
                'task_id' => 1,
                'student_id' => 7,
                'submission_text' => 'Entrega demo 1',
                'file_path' => null,
                'submitted_at' => now()->subDays(19),
                'grade' => 11,
                'teacher_feedback' => 'Retroalimentacion demo 1',
                'graded_at' => now()->subDays(18),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 2,
                'student_id' => 8,
                'submission_text' => 'Entrega demo 2',
                'file_path' => null,
                'submitted_at' => now()->subDays(18),
                'grade' => 12,
                'teacher_feedback' => 'Retroalimentacion demo 2',
                'graded_at' => now()->subDays(17),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 3,
                'student_id' => 9,
                'submission_text' => 'Entrega demo 3',
                'file_path' => null,
                'submitted_at' => now()->subDays(17),
                'grade' => 13,
                'teacher_feedback' => 'Retroalimentacion demo 3',
                'graded_at' => now()->subDays(16),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 4,
                'student_id' => 10,
                'submission_text' => 'Entrega demo 4',
                'file_path' => null,
                'submitted_at' => now()->subDays(16),
                'grade' => 14,
                'teacher_feedback' => 'Retroalimentacion demo 4',
                'graded_at' => now()->subDays(15),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 5,
                'student_id' => 11,
                'submission_text' => 'Entrega demo 5',
                'file_path' => null,
                'submitted_at' => now()->subDays(15),
                'grade' => 15,
                'teacher_feedback' => 'Retroalimentacion demo 5',
                'graded_at' => now()->subDays(14),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 6,
                'student_id' => 12,
                'submission_text' => 'Entrega demo 6',
                'file_path' => null,
                'submitted_at' => now()->subDays(14),
                'grade' => 16,
                'teacher_feedback' => 'Retroalimentacion demo 6',
                'graded_at' => now()->subDays(13),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 7,
                'student_id' => 13,
                'submission_text' => 'Entrega demo 7',
                'file_path' => null,
                'submitted_at' => now()->subDays(13),
                'grade' => 17,
                'teacher_feedback' => 'Retroalimentacion demo 7',
                'graded_at' => now()->subDays(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 8,
                'student_id' => 14,
                'submission_text' => 'Entrega demo 8',
                'file_path' => null,
                'submitted_at' => now()->subDays(12),
                'grade' => 18,
                'teacher_feedback' => 'Retroalimentacion demo 8',
                'graded_at' => now()->subDays(11),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 9,
                'student_id' => 15,
                'submission_text' => 'Entrega demo 9',
                'file_path' => null,
                'submitted_at' => now()->subDays(11),
                'grade' => 19,
                'teacher_feedback' => 'Retroalimentacion demo 9',
                'graded_at' => now()->subDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 10,
                'student_id' => 16,
                'submission_text' => 'Entrega demo 10',
                'file_path' => null,
                'submitted_at' => now()->subDays(10),
                'grade' => 20,
                'teacher_feedback' => 'Retroalimentacion demo 10',
                'graded_at' => now()->subDays(9),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 11,
                'student_id' => 17,
                'submission_text' => 'Entrega demo 11',
                'file_path' => null,
                'submitted_at' => now()->subDays(9),
                'grade' => 10,
                'teacher_feedback' => 'Retroalimentacion demo 11',
                'graded_at' => now()->subDays(8),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 12,
                'student_id' => 18,
                'submission_text' => 'Entrega demo 12',
                'file_path' => null,
                'submitted_at' => now()->subDays(8),
                'grade' => 11,
                'teacher_feedback' => 'Retroalimentacion demo 12',
                'graded_at' => now()->subDays(7),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 13,
                'student_id' => 19,
                'submission_text' => 'Entrega demo 13',
                'file_path' => null,
                'submitted_at' => now()->subDays(7),
                'grade' => 12,
                'teacher_feedback' => 'Retroalimentacion demo 13',
                'graded_at' => now()->subDays(6),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 14,
                'student_id' => 20,
                'submission_text' => 'Entrega demo 14',
                'file_path' => null,
                'submitted_at' => now()->subDays(6),
                'grade' => 13,
                'teacher_feedback' => 'Retroalimentacion demo 14',
                'graded_at' => now()->subDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 15,
                'student_id' => 7,
                'submission_text' => 'Entrega demo 15',
                'file_path' => null,
                'submitted_at' => now()->subDays(5),
                'grade' => 14,
                'teacher_feedback' => 'Retroalimentacion demo 15',
                'graded_at' => now()->subDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 16,
                'student_id' => 8,
                'submission_text' => 'Entrega demo 16',
                'file_path' => null,
                'submitted_at' => now()->subDays(4),
                'grade' => 15,
                'teacher_feedback' => 'Retroalimentacion demo 16',
                'graded_at' => now()->subDays(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 17,
                'student_id' => 9,
                'submission_text' => 'Entrega demo 17',
                'file_path' => null,
                'submitted_at' => now()->subDays(3),
                'grade' => 16,
                'teacher_feedback' => 'Retroalimentacion demo 17',
                'graded_at' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 18,
                'student_id' => 10,
                'submission_text' => 'Entrega demo 18',
                'file_path' => null,
                'submitted_at' => now()->subDays(2),
                'grade' => 17,
                'teacher_feedback' => 'Retroalimentacion demo 18',
                'graded_at' => now()->subDays(1),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 19,
                'student_id' => 11,
                'submission_text' => 'Entrega demo 19',
                'file_path' => null,
                'submitted_at' => now()->subDays(1),
                'grade' => 18,
                'teacher_feedback' => 'Retroalimentacion demo 19',
                'graded_at' => now()->subDays(0),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'task_id' => 20,
                'student_id' => 12,
                'submission_text' => 'Entrega demo 20',
                'file_path' => null,
                'submitted_at' => now()->subDays(0),
                'grade' => 19,
                'teacher_feedback' => 'Retroalimentacion demo 20',
                'graded_at' => now()->subDays(-1),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
