<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class TrainingsSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('trainings')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('trainings')->insert([
            [
                'course_id' => 1,
                'teacher_id' => 2,
                'administrator_id' => 1,
                'nrc' => '10001',
                'modality' => 'virtual',
                'start_date' => now()->subDays(60)->toDateString(),
                'end_date' => now()->subDays(15)->toDateString(),
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'teacher_id' => 3,
                'administrator_id' => 1,
                'nrc' => '10002',
                'modality' => 'presential',
                'start_date' => now()->subDays(50)->toDateString(),
                'end_date' => now()->subDays(5)->toDateString(),
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 3,
                'teacher_id' => 4,
                'administrator_id' => 1,
                'nrc' => '10003',
                'modality' => 'hybrid',
                'start_date' => now()->subDays(45)->toDateString(),
                'end_date' => now()->subDays(2)->toDateString(),
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'teacher_id' => 5,
                'administrator_id' => 1,
                'nrc' => '10004',
                'modality' => 'virtual',
                'start_date' => now()->startOfMonth()->addDays(3)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(3)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'teacher_id' => 6,
                'administrator_id' => 1,
                'nrc' => '10005',
                'modality' => 'presential',
                'start_date' => now()->startOfMonth()->addDays(4)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(4)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 6,
                'teacher_id' => 2,
                'administrator_id' => 1,
                'nrc' => '10006',
                'modality' => 'hybrid',
                'start_date' => now()->startOfMonth()->addDays(5)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(5)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 7,
                'teacher_id' => 3,
                'administrator_id' => 1,
                'nrc' => '10007',
                'modality' => 'virtual',
                'start_date' => now()->startOfMonth()->addDays(6)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(6)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 8,
                'teacher_id' => 4,
                'administrator_id' => 1,
                'nrc' => '10008',
                'modality' => 'presential',
                'start_date' => now()->startOfMonth()->addDays(7)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(7)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 9,
                'teacher_id' => 5,
                'administrator_id' => 1,
                'nrc' => '10009',
                'modality' => 'hybrid',
                'start_date' => now()->startOfMonth()->addDays(8)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(8)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 10,
                'teacher_id' => 6,
                'administrator_id' => 1,
                'nrc' => '10010',
                'modality' => 'virtual',
                'start_date' => now()->startOfMonth()->addDays(9)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(9)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 11,
                'teacher_id' => 2,
                'administrator_id' => 1,
                'nrc' => '10011',
                'modality' => 'presential',
                'start_date' => now()->startOfMonth()->addDays(10)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(10)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'teacher_id' => 3,
                'administrator_id' => 1,
                'nrc' => '10012',
                'modality' => 'hybrid',
                'start_date' => now()->startOfMonth()->addDays(11)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(11)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 13,
                'teacher_id' => 4,
                'administrator_id' => 1,
                'nrc' => '10013',
                'modality' => 'virtual',
                'start_date' => now()->startOfMonth()->addDays(12)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(12)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'teacher_id' => 5,
                'administrator_id' => 1,
                'nrc' => '10014',
                'modality' => 'presential',
                'start_date' => now()->startOfMonth()->addDays(13)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(13)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 15,
                'teacher_id' => 6,
                'administrator_id' => 1,
                'nrc' => '10015',
                'modality' => 'hybrid',
                'start_date' => now()->startOfMonth()->addDays(14)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(14)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 16,
                'teacher_id' => 2,
                'administrator_id' => 1,
                'nrc' => '10016',
                'modality' => 'virtual',
                'start_date' => now()->startOfMonth()->addDays(15)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(15)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 17,
                'teacher_id' => 3,
                'administrator_id' => 1,
                'nrc' => '10017',
                'modality' => 'presential',
                'start_date' => now()->startOfMonth()->addDays(16)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(16)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 18,
                'teacher_id' => 4,
                'administrator_id' => 1,
                'nrc' => '10018',
                'modality' => 'hybrid',
                'start_date' => now()->startOfMonth()->addDays(17)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(17)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 19,
                'teacher_id' => 5,
                'administrator_id' => 1,
                'nrc' => '10019',
                'modality' => 'virtual',
                'start_date' => now()->startOfMonth()->addDays(18)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(18)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 20,
                'teacher_id' => 6,
                'administrator_id' => 1,
                'nrc' => '10020',
                'modality' => 'presential',
                'start_date' => now()->startOfMonth()->addDays(19)->toDateString(),
                'end_date' => now()->startOfMonth()->addDays(19)->addDays(45)->toDateString(),
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
