<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;

class UsersSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('users')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('users')->insert([
                [
                    'person_id' => 1,
                    'username' => 'juan.gomez.admin',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 2,
                    'username' => 'maria.lopez.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 3,
                    'username' => 'luis.torres.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 4,
                    'username' => 'ana.rojas.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 5,
                    'username' => 'carlos.martinez.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 6,
                    'username' => 'laura.garcia.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 7,
                    'username' => 'miguel.hernandez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 8,
                    'username' => 'isabel.jimenez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 9,
                    'username' => 'diego.perez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 10,
                    'username' => 'valentina.ramirez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 11,
                    'username' => 'andres.flores.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 12,
                    'username' => 'camila.gutierrez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 13,
                    'username' => 'javier.reyes.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 14,
                    'username' => 'gabriela.morales.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 15,
                    'username' => 'roberto.ortiz.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 16,
                    'username' => 'natalia.delgado.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 17,
                    'username' => 'fernando.sanchez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 18,
                    'username' => 'monica.vargas.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 19,
                    'username' => 'eduardo.castro.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 20,
                    'username' => 'patricia.romero.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 21,
                    'username' => 'sofia.mendoza.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 22,
                    'username' => 'mateo.quispe.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 23,
                    'username' => 'lucia.navarro.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 24,
                    'username' => 'sebastian.vega.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 25,
                    'username' => 'daniela.campos.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 26,
                    'username' => 'ricardo.paredes.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 27,
                    'username' => 'elena.salazar.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 28,
                    'username' => 'piero.cardenas.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 29,
                    'username' => 'mariana.soto.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 30,
                    'username' => 'alonso.rivera.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 31,
                    'username' => 'estudiante31.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 32,
                    'username' => 'estudiante32.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 33,
                    'username' => 'estudiante33.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 34,
                    'username' => 'estudiante34.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 35,
                    'username' => 'estudiante35.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 36,
                    'username' => 'estudiante36.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 37,
                    'username' => 'estudiante37.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 38,
                    'username' => 'estudiante38.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 39,
                    'username' => 'estudiante39.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 40,
                    'username' => 'estudiante40.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 41,
                    'username' => 'estudiante41.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 42,
                    'username' => 'estudiante42.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 43,
                    'username' => 'estudiante43.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 44,
                    'username' => 'estudiante44.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 45,
                    'username' => 'estudiante45.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 46,
                    'username' => 'estudiante46.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 47,
                    'username' => 'estudiante47.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 48,
                    'username' => 'estudiante48.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 49,
                    'username' => 'estudiante49.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 50,
                    'username' => 'estudiante50.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 51,
                    'username' => 'estudiante51.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 52,
                    'username' => 'estudiante52.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 53,
                    'username' => 'estudiante53.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 54,
                    'username' => 'estudiante54.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 55,
                    'username' => 'estudiante55.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 56,
                    'username' => 'estudiante56.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 57,
                    'username' => 'estudiante57.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 58,
                    'username' => 'estudiante58.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 59,
                    'username' => 'estudiante59.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 60,
                    'username' => 'estudiante60.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 61,
                    'username' => 'estudiante61.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 62,
                    'username' => 'estudiante62.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 63,
                    'username' => 'estudiante63.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 64,
                    'username' => 'estudiante64.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 65,
                    'username' => 'estudiante65.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 66,
                    'username' => 'estudiante66.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
