<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;

class UsersSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('users')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('users')->insert([
                [
                    'person_id' => 1,
                    'username' => 'juan.lopez.admin',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 2,
                    'username' => 'maria.lopez.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 3,
                    'username' => 'luis.torres.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 4,
                    'username' => 'ana.rojas.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 5,
                    'username' => 'carlos.martinez.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 6,
                    'username' => 'laura.garcia.teacher',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 7,
                    'username' => 'miguel.hernandez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 8,
                    'username' => 'isabel.jimenez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',    
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 9,
                    'username' => 'diego.perez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 10,
                    'username' => 'valentina.ramirez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 11,
                    'username' => 'andres.flores.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 12,
                    'username' => 'camila.gutierrez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 13,
                    'username' => 'javier.reyes.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 14,
                    'username' => 'gabriela.morales.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 15,
                    'username' => 'roberto.ortiz.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 16,
                    'username' => 'natalia.delgado.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 17,
                    'username' => 'fernando.sanchez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 18,
                    'username' => 'monica.vargas.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 19,
                    'username' => 'eduardo.castro.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 20,
                    'username' => 'patricia.romero.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 21,
                    'username' => 'sofia.mendoza.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 22,
                    'username' => 'mateo.quispe.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 23,
                    'username' => 'lucia.navarro.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 24,
                    'username' => 'sebastian.vega.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 25,
                    'username' => 'daniela.campos.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 26,
                    'username' => 'ricardo.paredes.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 27,
                    'username' => 'elena.salazar.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 28,
                    'username' => 'piero.cardenas.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 29,
                    'username' => 'mariana.soto.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 30,
                    'username' => 'alonso.rivera.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 31,
                    'username' => 'valeria.montes.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 32,
                    'username' => 'nicolas.aguilar.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 33,
                    'username' => 'paula.espinoza.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 34,
                    'username' => 'alejandro.fuentes.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 35,
                    'username' => 'renata.ibarra.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 36,
                    'username' => 'hugo.medina.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 37,
                    'username' => 'isabella.ponce.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 38,
                    'username' => 'santiago.rios.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 39,
                    'username' => 'constanza.luna.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 40,
                    'username' => 'emilio.vera.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 41,
                    'username' => 'antonella.ramos.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 42,
                    'username' => 'fabian.acosta.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 43,
                    'username' => 'miriam.tapia.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 44,
                    'username' => 'ignacio.silva.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 45,
                    'username' => 'catalina.herrera.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 46,
                    'username' => 'oscar.blanco.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 47,
                    'username' => 'fernanda.moya.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 48,
                    'username' => 'tomas.cabrera.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 49,
                    'username' => 'ariana.diaz.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 50,
                    'username' => 'manuel.guerrero.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 51,
                    'username' => 'lorena.zambrano.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 52,
                    'username' => 'cristian.nieto.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 53,
                    'username' => 'julieta.palma.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 54,
                    'username' => 'rafael.cano.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 55,
                    'username' => 'pilar.serrano.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 56,
                    'username' => 'ivan.molina.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 57,
                    'username' => 'cecilia.roman.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 58,
                    'username' => 'dante.bravo.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 59,
                    'username' => 'marisol.leal.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 60,
                    'username' => 'cesar.miranda.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 61,
                    'username' => 'diana.sandoval.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 62,
                    'username' => 'hernan.palacios.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 63,
                    'username' => 'xiomara.cruces.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 64,
                    'username' => 'rodrigo.nunez.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 65,
                    'username' => 'beatriz.carrillo.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'person_id' => 66,
                    'username' => 'alberto.solis.student',
                    'password' => Hash::make('123456'),
                    'status' => 'A',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
